### ISSUE TITLE
Question : do you still need the `sha3` dependency ?

### ISSUE THREAD

**Issue by StefH** [wanderer/browserify-sha3#9]
https://github.com/wanderer/browserify-sha3/blob/master/package.json#L24

Just a question...

**Comment by fanatid** [comment]
`sha3` is used in tests: https://github.com/wanderer/browserify-sha3/blob/89ddbb423ff9c750bb3ee2d7e63499c98e111227/tests/index.js#L1

**Comment by StefH** [comment]
Why not using `js-sha3` also in the tests?

**Comment by fanatid** [comment]
because `sha3` is used for checking that `browserify-sha3` + `js-sha3` works as expected?
please check source file before ask questions
